name: CI Pipeline

on:
  push:
    branches:
      - zad1
  pull_request:
    branches:
      - zad1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run SuperLinter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: true
          VALIDATE_PYTHON_BLACK: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Run unit tests with coverage
        run: |
          coverage run testsPaymentProcessor.py
          coverage report -m
          coverage html
